#!/usr/bin/php
<?php

use Dframe\Console\Command;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/web/config.php';

$cli = ((new class () extends Command {
})->run($argv));

/* vim: set expandtab tabstop=2 shiftwidth=2: */
?>